jahller_artlas_homepage:
    path:     /home
    defaults: { _controller: JahllerArtlasBundle:Default:index }

jahller_artlas_info:
    path:     /info
    defaults: { _controller: JahllerArtlasBundle:Default:info }

jahller_artlas_piece_new:
    path:     /piece/new
    defaults: { _controller: JahllerArtlasBundle:Piece:new }

jahller_artlas_piece_show:
    path:     /piece/show/{id}
    defaults: { _controller: JahllerArtlasBundle:Piece:show }
    options:
        expose: true

jahller_artlas_piece_update:
    path:     /piece/update/{id}
    defaults: { _controller: JahllerArtlasBundle:Piece:update }
    options:
        expose: true

#jahller_artlas_piece_delete:
#    path:     /piece/delete/{id}
#    defaults: { _controller: JahllerArtlasBundle:Piece:delete }

jahller_artlas_piece_toggle_activate:
    path:     /piece/toggle_activate/{id}
    defaults: { _controller: JahllerArtlasBundle:Piece:toggleActivate }

jahller_artlas_backend_index:
    path:     /backend
    defaults: { _controller: JahllerArtlasBundle:Backend:index }

jahller_artlas_piece_rest:
    resource: "Jahller\\Bundle\\ArtlasBundle\\Controller\\PieceRestController"
    type:     annotation
    defaults:  { _format: json }
    options:
        expose: true