services:
    jahller.artlas.image.manager:
        class: Jahller\Bundle\ArtlasBundle\Service\ImageManager
        arguments:
          - @logger
          - %file_path_pieces%
        tags:
          - { name: monolog.logger, channel: jahller }

    jahller.artlas.helper.form:
        class: Jahller\Bundle\ArtlasBundle\Service\FormHelper

    jahller.artlas.manager.piece:
        class: Jahller\Bundle\ArtlasBundle\Document\Manager\PieceManager
        arguments:
            - @doctrine_mongodb.odm.document_manager

    jahller.artlas.repository.piece:
        class: Jahller\Bundle\ArtlasBundle\Document\Repository\PieceRepository
        arguments:
            - @doctrine_mongodb.odm.document_manager

    jahller.artlas.listener.image:
        class: Jahller\Bundle\ArtlasBundle\Listener\ImageListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - @jahller.attachment.manager.image
            - @jahller.artlas.manager.piece

    jahller.artlas.service.error_preparer:
        class: Jahller\Bundle\ArtlasBundle\Service\ErrorPreparer
        arguments:
            - @translator